import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        <nav className="bg-gray-800 p-4 text-white">
          <ul className="flex space-x-4">
            <li><a href="/dashboard" className="hover:text-gray-300">Dashboard</a></li>
            <li><a href="/profile" className="hover:text-gray-300">Perfil</a></li>
            <li><a href="/login" className="hover:text-gray-300">Login</a></li>
            <li><a href="/register" className="hover:text-gray-300">Registrar</a></li>
          </ul>
        </nav>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
